[project]
name = "canvas-photoshop-plugin"
description = "Photoshop companion plugin for XuanshangCanvas with ComfyUI and RunningHub compatibility."
version = "2.0.17"
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/someone97421/Canvas-photoshop-plugin"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "someone97421"
DisplayName = "Canvas Photoshop Plugin"
Icon = ""
